version: -0.0.0.{build}
image: Visual Studio 2019

environment:
  APPVEYOR_TOKEN:
    secure: EnZNz248FTxQXX+pCmZL7Ds5vFWwk8gkJASFBaQSos0=
  TITLE: 'MediaCat'
  PROJECT_NAME: 'MediaCat'
  ISS: 'mediacat-installer.iss'
  
skip_commits:
  files:
    - README.md
    
configuration:
  - Debug
  - Release
  
cache:
  - '%USERPROFILE%\.nuget\packages -> **.sln, **.csproj'  # preserve nuget folder (packages) unless the solution or projects change
    
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: $(APP_VERSION)
  assembly_file_version: $(APP_VERSION)
  assembly_informational_version: $(APP_VERSION_INFORMATIONAL)

install:
- ps: ./update-version.ps1

before_build:
  - nuget restore

build:
  project: '$(PROJECT_NAME).sln'
  verbosity: minimal

after_build:
  - ps: ./appveyor-build.ps1

test: off

artifacts:
  - path: '$(TITLE)-Portable_v*.zip'
    name: $(CONFIGURATION)-Portable
  - path: '$(TITLE)-Setup_v*.exe'
    name: $(CONFIGURATION)-Setup

deploy:
  release: '$(TITLE) v$(BUILD_VERSION)'
  tag: v$(BUILD_VERSION)
  provider: GitHub
  auth_token:
    secure: 2hE9Yq+4IOdsHm80lpYkQGR/uutZjdQUx79wU7oVbPLIBbJuGmgczTWq++mdCBa8
  artifact: /.*\.(exe|zip)/
  draft: true
  on:
    configuration: Release
    APPVEYOR_REPO_TAG: true