image: Visual Studio 2019

environment:
  APPVEYOR_TOKEN:
    secure: EnZNz248FTxQXX+pCmZL7Ds5vFWwk8gkJASFBaQSos0=

branches:
  only:
    - master
    - /v\d+\.\d+\.\d+/

skip_commits:
  files:
    - README.md
    
configuration:
  - Debug
  - Release
  
cache:
  - '%USERPROFILE%\.nuget\packages -> **.sln, **.csproj'  # preserve nuget folder (packages) unless the solution or projects change
    
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

install:
- ps: ./update-version.ps1

before_build:
  - nuget restore

build:
  project: 'MediaCat.sln'
  verbosity: minimal

after_build:
  - ps: ./appveyor-build.ps1

test: off

artifacts:
  - path: 'MediaCat-Portable_v*.zip'
    name: $(CONFIGURATION)-Portable
  - path: 'MediaCat-Setup_v*.exe'
    name: $(CONFIGURATION)-Setup

deploy:
  release: MediaCat v$(BUILD_VERSION)
  tag: v$(BUILD_VERSION)
  provider: GitHub
  auth_token:
    secure: 2hE9Yq+4IOdsHm80lpYkQGR/uutZjdQUx79wU7oVbPLIBbJuGmgczTWq++mdCBa8
  artifact: /.*\.(exe|zip)/
  draft: true
  on:
    APPVEYOR_REPO_TAG: true