image: Visual Studio 2019

environment:
  APPVEYOR_TOKEN:
    secure: EnZNz248FTxQXX+pCmZL7Ds5vFWwk8gkJASFBaQSos0=

skip_commits:
  files:
    - README.md
    
configuration:
  - Debug
  - Release
  
assembly_info:
  patch: true
  file: 'MediaCat\**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

install:
- ps: ./update-version.ps1

before_build:
  - nuget restore

build:
  project: 'MediaCat.sln'
  verbosity: minimal

test: off
deploy: off